name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Étape 3 : Effacer le cache npm
      - name: Clear npm cache
        run: npm cache clean --force

      # Étape 4 : Installer les dépendances
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Étape 5 : Construire le frontend
      - name: Build frontend
        run: npm run build

      # Étape 6 : Tester le frontend
      - name: Run tests
        run: npm test

      # Étape 7 : Construire l'image Docker du frontend
      - name: Build Docker image
        run: |
          docker build -t mariebaude/mpmt_front:v1.0 .

      # Étape 8 : Se connecter à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: mariebaude
          password: ${{ secrets.DOCKER_TOKEN }}

      # Étape 9 : Pousser l'image Docker sur Docker Hub
      - name: Push Docker image
        run: |
          docker push mariebaude/mpmt_front:v1.0
