name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Run tests
        run: |
          npm test

      - name: Build Docker image
        run: |
          docker build -t mariebaude/mpmt_front:v1.0 .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: mariebaude
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        run: |
          docker push mariebaude/mpmt_front:v1.0